# config file for CICD provisioning script

# dnac structure elements can reference
# environmnet variables, i.e.
#   password: '%ENV(DNAC_PASSWORD)'
#
dnac:
  base_url: https://10.122.20.139
  version: 2.2.3.3
  username: admin
  password: '%ENV{DNAC_PASSWORD}'
  verify: False

# DNAC project we maintain
template_project: CICD-GIT

notify:
  # specify room_id and/or WebexTeams person email
  room_id: Y2lzY29zcGFyazovL3VzL1JPT00vYmUwODAzMzAtNTQ5MS0xMWVjLWE2NDItMTE5ZTc1MDcwYjU0
  #persons:
  #  - phphasuk@cisco.com

